name: Test and publish

on:
  push:
    paths:
      - '.github/workflows/test-publish.yml'
      - 'MathGmp.Native.*/**'
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish package'
        default: false
        required: false 
        type: boolean

jobs:
  test:
    env:
      BUILD_CONFIG: release
    name: Test and publish if required
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v3
    
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        working-directory: MathGmp.Native
        run: dotnet build -c ${{ env.BUILD_CONFIG }} --no-restore -p:ContinuousIntegrationBuild=true
    
      - name: Test
        working-directory: MathGmp.Native.UnitTests
        run: dotnet test -c ${{ env.BUILD_CONFIG }} --no-restore

      - name: Publish
        if: ${{ inputs.publish }}
        working-directory: MathGmp.Native
        run: |
          dotnet pack -c ${{ env.BUILD_CONFIG }} --no-build
          dotnet nuget push bin/${{ env.BUILD_CONFIG }}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
